/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package es.goda87.adventofcode2020.app

import es.goda87.adventofcode.*

fun main() {
    println(solvePuzzlesToString(true, *puzzles))
}

private val puzzles = listOf<Pair<Puzzle, CharSequence>>(
    ReportRepairPuzzle() to "2020day1input.txt",
    ReportRepairPuzzle(3) to "2020day1input.txt",
    PasswordPhilosophyPuzzle() to "2020day2input.txt",
    PasswordPhilosophy2Puzzle() to "2020day2input.txt",
    TobogganTrajectoryPuzzle() to "2020day3input.txt",
    TobogganTrajectory2Puzzle() to "2020day3input.txt"
).map {
    it.first to readFileAsString(it.second)
}.toTypedArray()
