/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package es.goda87.adventofcode2020.app

import es.goda87.adventofcode.Puzzle
import es.goda87.adventofcode.ReportRepairPuzzle

fun main() {
    println(solvePuzzlesToString(true, *puzzles))
}

private val puzzles = listOf<Pair<Puzzle, CharSequence>>(
    ReportRepairPuzzle() to "2020day1Input.txt",
    ReportRepairPuzzle(3) to "2020day1Input.txt"
).map {
    it.first to readFileAsString(it.second)
}.toTypedArray()
