/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("es.goda87.adventofcode2020.kotlin-application-conventions")
}

dependencies {
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("es.goda87.adventofcode2020.app.AppKt")
}
